import * as z from "zod";

export const supportLogFormSchema = z.object({
  recipt_no: z.string().optional(),
  receipt_date: z.string().optional(),
  enroll_name: z.string().optional(),
  enroll_address: z.string().optional(),
  enroll_contact: z.string().optional(),
  enroll_relation: z.string().optional(),
  enroll_info: z.string().optional(),
  manager_name: z.string().optional(),
  manager_contact: z.string().optional(),
  manager_email: z.string().optional(),
  support_period: z.string().optional(),
  support_amount: z.union([z.string(), z.number()]).optional(),
  support_content: z.string().optional(),
  report_title: z.string().optional(),
  report_date: z.string().optional(),
  report_inst: z.string().optional(),
  report_no: z.string().optional(),
  significant: z.string().optional(),
  log_status: z.union([z.string(), z.number()]).optional(),
  changed_column: z.string().optional(),
});

export const supportLogDefaultValue = {
  recipt_no: "",
  receipt_date: "",
  enroll_name: "",
  enroll_address: "",
  enroll_contact: "",
  enroll_relation: "",
  enroll_info: "",
  manager_name: "",
  manager_contact: "",
  manager_email: "",
  support_period: "",
  support_amount: "",
  support_content: "",
  report_title: "",
  report_date: "",
  report_inst: "",
  report_no: "",
  significant: "",
  log_status: "",
  changed_column: "",
};
