"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./provider/queryclientProvider";
// import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useEffect } from "react";
import { loadKakaoSdk } from "./utils/kakao";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    loadKakaoSdk()
      .then(() => {
        console.log("kakao sdk loaded and initialized");
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-full min-h-screen flex justify-center items-center">
          <QueryProvider>
            {children}
            {/* <ToastContainer /> */}
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
